import { app, BrowserWindow, ipcMain, net } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const LOGIN_WINDOW_WEBPACK_ENTRY: string;
declare const LOGIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const HOME_WINDOW_WEBPACK_ENTRY: string;
declare const HOME_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

declare const REGISTER_WINDOW_WEBPACK_ENTREY: string;
declare const REGISTER_WINDOW_PRELOAD_WEBPACK_ENTREY: string;
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let loginWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  loginWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: LOGIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  loginWindow.loadURL(LOGIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  loginWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

ipcMain.handle('nav:toHome', async () => {
  if (!loginWindow) return;
  // opcional: cambia preload si home lo requiere
  // mainWindow.webContents.session.flushStorageData(); // si necesitas limpiar algo
  await loginWindow.loadURL(HOME_WINDOW_WEBPACK_ENTRY);
  return true;
});

ipcMain.handle('nav:toLogin', async () => {
  if (!loginWindow) return;
  // opcional: cambia preload si home lo requiere
  // mainWindow.webContents.session.flushStorageData(); // si necesitas limpiar algo
  await loginWindow.loadURL(LOGIN_WINDOW_WEBPACK_ENTRY);
  return true;
});

ipcMain.handle('http:get', async (_e, url: string, options?: any) => {
  const res = await net.fetch(url, { method: 'GET', ...options });
  const body = await res.json(); // o .text() / .arrayBuffer()
  // Convierte cabeceras a objeto simple si quieres retornarlas
  return { status: res.status, ok: res.ok, body };
});

ipcMain.handle('http:post', async (_e, url: string, payload: any, options?: any) => {
  console.log('POST', url, payload, options);
  const res = await net.fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...(options?.headers || {}) },
    body: JSON.stringify(payload),
    ...options
  });
  return { status: res.status, ok: res.ok, body: await res.json()};
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
